/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;
import util.ConnectionFactory;

/**
 * @author Dani
 */

public class Main {
    public static void main(String[] args) {
        
           //TODO code application logic here
           
           
//         ProjectController projectController = new ProjectController();
//        
//         Project project = new Project();
//         project.setName("Projeto teste");
//         project.setDescription("description");
//         projectController.save(project);
         
         ProjectController projectController = new ProjectController();

         Project project = new Project();
         project.setId(12);
         project.setName("Projeto teste");
         project.setDescription("description");
         
         
         project.setName("Novo nome do projeto");
         projectController.update(project);
//         
         List<Project>projects = projectController.getAll();
         System.out.println("Total de projetos = " + projects.size());
         
         projectController.removeById(12);
         
         TaskController taskcontroller = new TaskController();
         
         Task task = new Task();
         task.setIdProject(2);
         task.setName("Criar as telas da aplicação");
         task.setDescription("Devem ser criadas telas para os cadastros");
         task.setNotes("Sem notas");
         task.setIsCompleted(false);
         task.setDeadline(new Date());
         
         taskcontroller.save(task);
         
         task.setName("Alterar telas da aplicação");
         taskcontroller.update(task);
         List<Task>tasks = taskcontroller.getAll(12);
         System.out.println("Total de tarefas - " + tasks.size());
         
                 
    }
    
}
